# Generated by Django 5.2.16 on 2026-07-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_orderproduct_quantity'),
        ('foodcartapp', '0064_alter_orderproduct_order'),
        ('foodcartapp', '0065_alter_orderproduct_order'),
    ]

    operations = [
    ]
