# Generated by Django 5.2.15 on 2026-06-14 16:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_order_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='номер телефона'),
        ),
    ]
