# Generated by Django 5.2.15 on 2026-06-14 21:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_address_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона'),
        ),
    ]
